version: '0.0.1'

services:                           # サービスを定義しますという決まり文句
  rattle:                           # pythonという名前でサービスを定義
    image: rattle                   # イメージのREPOSITORY名:TAG名を指定
    build: ..                       # Dockerfileを相対パスで指定
    container_name: rattle          # 作成されるコンテナ名を指定
    working_dir: /workspace/rattle         # 作業ディレクトリを指定
    volumes:                        # マウントするファイルを指定する
      - ../:/workspace/rattle       # ローカルPCのsrc:コンテナのworkspace/src
    tty: true                       # コンテナを起動し続ける